### ISSUE TITLE
 collision detection

### ISSUE THREAD

**Issue by Wayne-xixi** [harish1696/d-orca#4]
Hello, thank you very much for the efforts! The video looks very cool! Just a question, how do you make collision detection and realize free collision? Because I don’t find the referenced code.
Thanks!

**Comment by harish1696** [comment]
Collision detection is done using the `rvo2_3d` and `PQP` libraries which you can find under the `libs` directory.

**Comment by Wayne-xixi** [comment]
Thank you!
