### ISSUE TITLE
Redeclarations of math functions in PQP_Compile.h

### ISSUE THREAD

**Issue by yhdurkaya** [harish1696/d-orca#5]
There are errors in catkin_make.
In PQP_Compile.h, inline  sqrt, sin, cos, fabs are created but also math is included so that it throws "conflicts with a previous declaration" because of redeclaration.

https://gamma.umd.edu/researchdirections/aerialswarm/install 
I followed the instructions in here and at the last instruction, catkin_make throws error.

![Screenshot from 2020-01-09 14-09-24](https://user-images.githubusercontent.com/47098320/72066714-57848b00-32f2-11ea-892f-f7900536bb99.png)

I use Ubuntu 18.04 and ROS Melodic.

**Comment by Kevinskwk** [comment]
Hi! I think an easy fix should be commenting out lines 47 - 50 in the file `libs/pqp/PQP_Compile.h`.
https://github.com/harish1696/d-orca/blob/master/libs/pqp/PQP_Compile.h#L47-L50

**Comment by yhdurkaya** [comment]
I forgot I've posted this. Sorry for all the folks who saw this and couldn't find a solution. I fixed it back in the day, the same way @Kevinskwk but forgot to post it here:) Just comment out and you'll be fine.
